language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - ./node_modules
dist: trusty
sudo: required
branches:
  only:
    - master
before_install:
  - yarn global add @angular/cli firebase-tools

jobs:
  include:
    - stage: 'Tests'
      name: 'Lint Tests'
      script: yarn lint
    - script: yarn test-headless
      name: 'Unit Tests'
    - script: yarn e2e-tabu --headless
      name: 'E2E Tests'

    - stage: 'Build'
      script: yarn build --prod --aot

    - stage: 'Deploy'
      skip_cleanup: true
      script: firebase deploy --token $FIREBASE_TOKEN
