language: node_js
node_js:
  - '8'
cache:
  npm: true
  yarn: true
  directories:
    - '~/.cache'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - yarn global add @angular/cli
script:
  - yarn lint
  - yarn test
  - yarn e2e
  - yarn build --prod --base-href https://github.com/MichaelWarneke/tabularius/

deploy:
  provider: firebase
  token:
    secure: $FB_TOKEN
