language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - '~/.cache'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - yarn global add @angular/cli firebase-tools

jobs:
  include:
    - stage: 'Tests'
      name: 'Lint Tests'
      script: yarn lint
    - script: yarn test-headless
      name: 'Unit Tests'
    - script: yarn e2e-tabu --headless
      name: 'E2E Tests'

    - stage: BuildAndDeploy
      script:
        - yarn build --prod --aot
        - firebase deploy --token $FIREBASE_TOKEN
