language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - '~/.cache'
dist: trusty
sudo: required
branches:
  only:
    - master
before_install:
  - yarn global add @angular/cli
  - yarn global add firebase-tools

jobs:
  include:
    - stage: LintTest
      script:
        - yarn lint
    - stage: UnitTest
      script:
        - yarn test
    - stage: E2ETest
      script:
        - yarn e2e

    - stage: BuildProduction
      script:
        - yarn build --prod --base-href https://github.com/MichaelWarneke/tabularius/

    - stage: Deploy
      script:
        - firebase deploy --token $FIREBASE_TOKEN
