language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - '~/.cache'
dist: trusty
sudo: required
branches:
  only:
    - master
before_install:
  - yarn global add @angular/cli
  - yarn global add firebase-tools

jobs:
  include:
    - stage: "Tests"
      name: "Lint Tests"
      script: - yarn lint
    - script: - yarn test
      name: "Unit Tests"
    - script: - yarn e2e
      name: "E2E Tests"

    - stage: BuildAndDeploy
      script:
        - yarn build --prod --base-href https://github.com/MichaelWarneke/tabularius/
        - firebase deploy --token $FIREBASE_TOKEN
