language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - '~/.cache'
    - ./node_modules
    - ./dist
dist: trusty
sudo: required
branches:
  only:
    - master
install:
  - npm ci
  - yarn global add @angular/cli firebase-tools

jobs:
  include:
    - stage: 'Tests'
      name: 'Lint Tests'
      script: yarn lint
    - script: yarn test-headless
      name: 'Unit Tests'
    - script: yarn e2e-tabu --headless
      name: 'E2E Tests'

    - stage: 'Build'
      script: yarn build --prod --aot

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master
